# Site settings
title: test title
description: test description
url: "https://0xblz.github.io"
baseurl: "/quick-web"

# Build settings
markdown: kramdown
permalink: default
exclude: [README.md, Gemfile, Gemfile.lock]

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  experiences:
    output: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed 